name: MathSphere CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install backend dependencies
        run: cd server && npm ci

      - name: Run backend linter
        run: cd server && npm run lint || echo "Linting issues detected"

      - name: Run backend tests
        run: cd server && npm test
        env:
          NODE_ENV: test
          JWT_SECRET: test_jwt_secret
          JWT_EXPIRES_IN: 1h
          MONGODB_URI: mongodb://localhost:27017/mathsphere_test

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: backend-coverage
          path: server/coverage/

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install frontend dependencies
        run: cd client && npm ci

      - name: Run frontend linter
        run: cd client && npm run lint || echo "Linting issues detected"

      - name: Run frontend tests
        run: cd client && npm test -- --watchAll=false
        env:
          NODE_ENV: test

      - name: Build frontend
        run: cd client && npm run build
        env:
          CI: false  # Prevents build from failing on warnings
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: frontend-coverage
          path: client/coverage/ 